### ISSUE TITLE
I did clone but I do not see the project directory. Where to find?

### ISSUE THREAD

**Issue by Amitloh** [margiki/NHS-nodejs-webapp#1]
Open the Terminal (Linux & MacOS) or PowerShell (Windows) and change directory to the project folder(where is this?).
Type ‘npm install’ in the Terminal (PowerShell) and press Enter. All the dependencies would be installed.

**Comment by andreimargeloiu** [comment]
Cd to the project folder, meaning the folder you download from Github.

**Comment by Amitloh** [comment]
Thanks! Its working now! Is mean stack really good for building complex healthcare apps? I mean in terms of security, ssl, large databases, multiple clients application, code management etc and long term stability. Can we build both web and mobile apps? Currently whatever I build is on dotnet and sharepoint and sql/mysql but I want to explore mean stack for really mean complex applications. For example in your patient with room grid If I want to add inline editing, export to excel/pdf, add an hyperlink to actual record then is that going to be easy enough?(plus show/hide form controls based on user/security etc.)

**Comment by andreimargeloiu** [comment]
I am not an expert in healthcare systems, but I would not advice Mean stack for healthcare applications. It has all feature that you might want. However, I think that the industry uses Java or C# predominantly for the backend.

**Comment by Amitloh** [comment]
Thank you!
